/polyx_ns:
  polyx_node_talker:
    ros__parameters:
      use_sim_time: False
      eth_enable: True
      eth_server: "172.17.192.1" #"10.1.10.194"
      eth_port: "8888"
      polyx_output: 0xFF
